CC = c++ -std=c++11

all: Actividad_1

Actividad_1: Actividad_1.o
	$(CC) Actividad_1.o -o Actividad_1.out

Actividad_1.o: Actividad_1.cpp
	$(CC) -c Actividad_1.cpp

clean:
	rm -f Actividad_1.out Actividad_1.o